name: Build Docker image
on: push
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: docker build . -t ghcr.io/hspsh/spotty-kiwi
