name: Build and push Docker image
on: push
jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: docker build . -t hspsh/spotty-kiwi
      - run: echo "::set-output name=TAG::$(git describe --tags 2>/dev/null)"
        name: Check if commit is tagged
        id: check-tag
      - if: ${{ steps.check-tag.outputs.TAG != '' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ steps.check-tag.outputs.TAG != '' }}
        name: Push image
        run: |
          TAG=${{ steps.check-tag.outputs.TAG }}
          docker tag hspsh/spotty-kiwi ghcr.io/hspsh/spotty-kiwi:$TAG
          docker push ghcr.io/hspsh/spotty-kiwi:$TAG
