name: Lint and format sources
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn
        name: Install dependencies
      - run: yarn eslint '**/*.ts'
        name: Lint sources
      - run: yarn prettier '**/*.ts' --check
        name: Format sources
