name: Push Docker image
on:
  push:
    tags: [v*]

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: docker build . -t hspsh/spotty-kiwi
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker tag hspsh/spotty-kiwi ghcr.io/hspsh/spotty-kiwi:$(git describe --tags --abbrev=0)
      - run: docker push ghcr.io/hspsh/spotty-kiwi:$(git describe --tags --abbrev=0)
